### ISSUE TITLE
Codecov fails on all pull requests

### ISSUE THREAD

**Issue by epassaro** [tardis-sn/carsus#298]
Fails on all pull requests with the same diff: ~-7%

The base commit is always 275c383d26dad3386a5b75cf399f8f7c31b2c51c (why?),

**Comment by chvogl** [comment]
It looks like the codecov reports are uploaded to tardis instead of carsus (see e.g. commit 79af39c8 at https://app.codecov.io/github/tardis-sn/tardis/commits). The latest report that was uploaded to TARDIS (https://app.codecov.io/gh/tardis-sn/carsus/commits) is two years old and is the one that is used as a reference whenever codecov is run. @epassaro is it possible that there is something wrong with the CODECOV_TOKEN or do you have another idea what is going wrong?

**Comment by chvogl** [comment]
I updated the CODECOV_TOKEN (which I guess was set to the TARDIS value). Everything seems to work as intended now.
